---
- name: Install Docker and Git on Debian 12 (AWS Instance)
  hosts: webservers  # Replace 'webservers' with your actual host group or use 'localhost' for local execution
  become: yes  # Ensure root privileges for installation

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version installed: {{ docker_version.stdout }}"

    - name: Verify Git installation
      command: git --version
      register: git_version

    - name: Display Git version
      debug:
        msg: "Git version installed: {{ git_version.stdout }}"

    - name: Install acl
      apt:
        name: acl
        state: present
        update_cache: yes
